# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: numerics.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qai_hub_models_cli.proto.shared import range_pb2 as shared_dot_range__pb2
from qai_hub_models_cli.proto.shared import precision_pb2 as shared_dot_precision__pb2
from qai_hub_models_cli.proto.shared import runtime_pb2 as shared_dot_runtime__pb2
from qai_hub_models_cli.proto.shared import tool_versions_pb2 as shared_dot_tool__versions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enumerics.proto\x12\x05qaihm\x1a\x12shared/range.proto\x1a\x16shared/precision.proto\x1a\x14shared/runtime.proto\x1a\x1ashared/tool_versions.proto\"s\n\x19NumericsAccuracyBenchmark\x12\x14\n\x0c\x64\x61taset_name\x18\x01 \x01(\t\x12\x13\n\x0bmetric_name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x0c\n\x04unit\x18\x04 \x01(\t\x12\x0e\n\x06source\x18\x05 \x01(\t\"\xfd\x05\n\rModelNumerics\x12\x14\n\x0c\x61ihm_version\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x34\n\x07metrics\x18\x03 \x03(\x0b\x32#.qaihm.ModelNumerics.NumericsMetric\x1a\x8d\x05\n\x0eNumericsMetric\x12\x14\n\x0c\x64\x61taset_name\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x61taset_link\x18\x02 \x01(\t\x12!\n\x19\x64\x61taset_split_description\x18\x03 \x01(\t\x12\x13\n\x0bmetric_name\x18\x04 \x01(\t\x12\x1a\n\x12metric_description\x18\x05 \x01(\t\x12\x13\n\x0bmetric_unit\x18\x06 \x01(\t\x12(\n\x0cmetric_range\x18\x07 \x01(\x0b\x32\x12.qaihm.DoubleRange\x12(\n\x1bmetric_enablement_threshold\x18\x08 \x01(\x01H\x00\x88\x01\x01\x12\x1c\n\x0f\x62\x65nchmark_value\x18\t \x01(\x01H\x01\x88\x01\x01\x12\x1b\n\x13num_partial_samples\x18\n \x01(\x05\x12\x1c\n\x14partial_torch_metric\x18\x0b \x01(\x01\x12Q\n\x0e\x64\x65vice_metrics\x18\x0c \x03(\x0b\x32\x39.qaihm.ModelNumerics.NumericsMetric.DeviceNumericsMetrics\x1a\xb1\x01\n\x15\x44\x65viceNumericsMetrics\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12#\n\tprecision\x18\x02 \x01(\x0e\x32\x10.qaihm.Precision\x12\x1f\n\x07runtime\x18\x03 \x01(\x0e\x32\x0e.qaihm.Runtime\x12\x16\n\x0epartial_metric\x18\x04 \x01(\x01\x12*\n\rtool_versions\x18\x05 \x01(\x0b\x32\x13.qaihm.ToolVersionsB\x1e\n\x1c_metric_enablement_thresholdB\x12\n\x10_benchmark_valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'numerics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NUMERICSACCURACYBENCHMARK']._serialized_start=119
  _globals['_NUMERICSACCURACYBENCHMARK']._serialized_end=234
  _globals['_MODELNUMERICS']._serialized_start=237
  _globals['_MODELNUMERICS']._serialized_end=1002
  _globals['_MODELNUMERICS_NUMERICSMETRIC']._serialized_start=349
  _globals['_MODELNUMERICS_NUMERICSMETRIC']._serialized_end=1002
  _globals['_MODELNUMERICS_NUMERICSMETRIC_DEVICENUMERICSMETRICS']._serialized_start=773
  _globals['_MODELNUMERICS_NUMERICSMETRIC_DEVICENUMERICSMETRICS']._serialized_end=950
# @@protoc_insertion_point(module_scope)
