# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
SPDX-License-Identifier: BSD-3-Clause
---------------------------------------------------------------------
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import shared.precision_pb2
import shared.range_pb2
import shared.runtime_pb2
import shared.tool_versions_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class NumericsAccuracyBenchmark(google.protobuf.message.Message):
    """Expected accuracy benchmark for a model on a specific dataset/metric.
    Used in info.yaml to set the expected value scorecard checks against.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATASET_NAME_FIELD_NUMBER: builtins.int
    METRIC_NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    dataset_name: builtins.str
    metric_name: builtins.str
    value: builtins.float
    unit: builtins.str
    source: builtins.str
    """Where this benchmark value came from (e.g., a URL to the paper or
    model card, or "AI Hub Models Reference Eval" for scorecard-derived values).
    """
    def __init__(
        self,
        *,
        dataset_name: builtins.str = ...,
        metric_name: builtins.str = ...,
        value: builtins.float = ...,
        unit: builtins.str = ...,
        source: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dataset_name", b"dataset_name", "metric_name", b"metric_name", "source", b"source", "unit", b"unit", "value", b"value"]) -> None: ...

global___NumericsAccuracyBenchmark = NumericsAccuracyBenchmark

@typing.final
class ModelNumerics(google.protobuf.message.Message):
    """Schema for numerics.yaml — model numerical accuracy metrics."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class NumericsMetric(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class DeviceNumericsMetrics(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            DEVICE_FIELD_NUMBER: builtins.int
            PRECISION_FIELD_NUMBER: builtins.int
            RUNTIME_FIELD_NUMBER: builtins.int
            PARTIAL_METRIC_FIELD_NUMBER: builtins.int
            TOOL_VERSIONS_FIELD_NUMBER: builtins.int
            device: builtins.str
            precision: shared.precision_pb2.Precision.ValueType
            runtime: shared.runtime_pb2.Runtime.ValueType
            partial_metric: builtins.float
            @property
            def tool_versions(self) -> shared.tool_versions_pb2.ToolVersions:
                """The tool versions used to generate this result. Cross-referenced from
                the matching perf record (same device/precision/runtime) at build time,
                since numerics is produced without tool-version info of its own.

                Unset in numerics protos from releases before 0.57.0.
                """

            def __init__(
                self,
                *,
                device: builtins.str = ...,
                precision: shared.precision_pb2.Precision.ValueType = ...,
                runtime: shared.runtime_pb2.Runtime.ValueType = ...,
                partial_metric: builtins.float = ...,
                tool_versions: shared.tool_versions_pb2.ToolVersions | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["tool_versions", b"tool_versions"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["device", b"device", "partial_metric", b"partial_metric", "precision", b"precision", "runtime", b"runtime", "tool_versions", b"tool_versions"]) -> None: ...

        DATASET_NAME_FIELD_NUMBER: builtins.int
        DATASET_LINK_FIELD_NUMBER: builtins.int
        DATASET_SPLIT_DESCRIPTION_FIELD_NUMBER: builtins.int
        METRIC_NAME_FIELD_NUMBER: builtins.int
        METRIC_DESCRIPTION_FIELD_NUMBER: builtins.int
        METRIC_UNIT_FIELD_NUMBER: builtins.int
        METRIC_RANGE_FIELD_NUMBER: builtins.int
        METRIC_ENABLEMENT_THRESHOLD_FIELD_NUMBER: builtins.int
        BENCHMARK_VALUE_FIELD_NUMBER: builtins.int
        NUM_PARTIAL_SAMPLES_FIELD_NUMBER: builtins.int
        PARTIAL_TORCH_METRIC_FIELD_NUMBER: builtins.int
        DEVICE_METRICS_FIELD_NUMBER: builtins.int
        dataset_name: builtins.str
        """Dataset"""
        dataset_link: builtins.str
        dataset_split_description: builtins.str
        metric_name: builtins.str
        """Metric definition"""
        metric_description: builtins.str
        metric_unit: builtins.str
        metric_enablement_threshold: builtins.float
        """Maximum allowed deviation between torch and device accuracy, or
        between actual accuracy and the benchmark value.
        Paths exceeding this threshold are disabled by the scorecard.
        """
        benchmark_value: builtins.float
        """Expected accuracy from info.yaml's numerics_benchmark."""
        num_partial_samples: builtins.int
        """Torch reference values"""
        partial_torch_metric: builtins.float
        @property
        def metric_range(self) -> shared.range_pb2.DoubleRange: ...
        @property
        def device_metrics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ModelNumerics.NumericsMetric.DeviceNumericsMetrics]:
            """Per-device results"""

        def __init__(
            self,
            *,
            dataset_name: builtins.str = ...,
            dataset_link: builtins.str = ...,
            dataset_split_description: builtins.str = ...,
            metric_name: builtins.str = ...,
            metric_description: builtins.str = ...,
            metric_unit: builtins.str = ...,
            metric_range: shared.range_pb2.DoubleRange | None = ...,
            metric_enablement_threshold: builtins.float | None = ...,
            benchmark_value: builtins.float | None = ...,
            num_partial_samples: builtins.int = ...,
            partial_torch_metric: builtins.float = ...,
            device_metrics: collections.abc.Iterable[global___ModelNumerics.NumericsMetric.DeviceNumericsMetrics] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_benchmark_value", b"_benchmark_value", "_metric_enablement_threshold", b"_metric_enablement_threshold", "benchmark_value", b"benchmark_value", "metric_enablement_threshold", b"metric_enablement_threshold", "metric_range", b"metric_range"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_benchmark_value", b"_benchmark_value", "_metric_enablement_threshold", b"_metric_enablement_threshold", "benchmark_value", b"benchmark_value", "dataset_link", b"dataset_link", "dataset_name", b"dataset_name", "dataset_split_description", b"dataset_split_description", "device_metrics", b"device_metrics", "metric_description", b"metric_description", "metric_enablement_threshold", b"metric_enablement_threshold", "metric_name", b"metric_name", "metric_range", b"metric_range", "metric_unit", b"metric_unit", "num_partial_samples", b"num_partial_samples", "partial_torch_metric", b"partial_torch_metric"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_benchmark_value", b"_benchmark_value"]) -> typing.Literal["benchmark_value"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_metric_enablement_threshold", b"_metric_enablement_threshold"]) -> typing.Literal["metric_enablement_threshold"] | None: ...

    AIHM_VERSION_FIELD_NUMBER: builtins.int
    MODEL_ID_FIELD_NUMBER: builtins.int
    METRICS_FIELD_NUMBER: builtins.int
    aihm_version: builtins.str
    model_id: builtins.str
    @property
    def metrics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ModelNumerics.NumericsMetric]: ...
    def __init__(
        self,
        *,
        aihm_version: builtins.str = ...,
        model_id: builtins.str = ...,
        metrics: collections.abc.Iterable[global___ModelNumerics.NumericsMetric] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["aihm_version", b"aihm_version", "metrics", b"metrics", "model_id", b"model_id"]) -> None: ...

global___ModelNumerics = ModelNumerics
